# Generated by Django 4.2.7 on 2023-11-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('member_pw', models.CharField(max_length=100)),
                ('member_repw', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('jumin', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('stock_cd', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stock_nm', models.CharField(max_length=20)),
                ('market_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_cd', models.CharField(max_length=20)),
                ('stock_dt', models.DateField()),
                ('stock_volume', models.BigIntegerField()),
                ('stock_rate', models.FloatField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('stock_cd', 'stock_dt')},
            },
        ),
        migrations.CreateModel(
            name='CategoryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_cd', models.CharField(max_length=20)),
                ('category_nm', models.CharField(max_length=20)),
                ('category_total', models.BigIntegerField()),
            ],
            options={
                'unique_together': {('stock_cd',)},
            },
        ),
    ]
